import type { AuditArea, AuditEvent, AuditSource } from '@ppe/api-client'
import { localized, plural } from '@ppe/i18n'

/**
 * How recorded changes read, in each language. Each event is an action
 * ("Price changed"), shown beside the record's name rather than inside a
 * sentence, so names are never inflected.
 */
const en = {
  events: {
    'user.created': 'User added',
    'user.updated': 'User details changed',
    'user.roles_changed': 'Roles changed',
    'user.activated': 'User activated',
    'user.deactivated': 'User deactivated',
    'user.password_changed': 'Password changed by its user',
    'user.password_reset': 'Password reset',
    'user.deleted': 'User deleted',
    'role.created': 'Role added',
    'role.updated': 'Role changed',
    'role.deleted': 'Role deleted',
    'employee.created': 'Employee added',
    'employee.updated': 'Employee details changed',
    'employee.sizes_changed': 'Sizes changed',
    'employee.deleted': 'Employee deleted',
    'catalogue.created': 'Item added',
    'catalogue.updated': 'Item details changed',
    'catalogue.price_changed': 'Price changed',
    'catalogue.activated': 'Item activated',
    'catalogue.deactivated': 'Item deactivated',
    'catalogue.deleted': 'Item deleted',
    'item_set.created': 'Item set added',
    'item_set.updated': 'Item set changed',
    'item_set.deleted': 'Item set deleted',
    'order.ordered': 'Marked as ordered',
    'order.confirmation_link_created': 'Confirmation link created',
    'order.given': 'Given',
    'order.deleted': 'Order deleted',
    'settings.supplier_chat_changed': 'Supplier’s WhatsApp group changed',
    'access_review.completed': 'Access reviewed',
    'audit.exported': 'Audit log exported',
    'audit.purged': 'Old changes deleted',
  } satisfies Record<AuditEvent, string>,
  areas: {
    users: 'Users and roles',
    employees: 'Employees',
    catalogue: 'Item Catalogue',
    item_sets: 'Item Sets',
    orders: 'Orders',
    settings: 'Settings',
    security: 'Security',
    audit: 'Audit log',
  } satisfies Record<AuditArea, string>,
  sources: {
    workwear: 'Workwear & Equipment',
    admin: 'Administration',
    api: 'API',
    public_link: 'Confirmation link',
    system: 'System',
  } satisfies Record<AuditSource, string>,
  fields: {
    first_name: 'First name',
    last_name: 'Last name',
    code: 'Code',
    preferred_language: 'Preferred language',
    notes_changed: 'Notes',
    height_cm: 'Height',
    clothing_size: 'Clothing size',
    shoe_size: 'Shoe size',
    name: 'Name',
    email: 'Email',
    language: 'Language',
    role_ids: 'Roles',
    is_active: 'Active',
    description: 'Description',
    permissions: 'Permissions',
    details: 'Details',
    size_group: 'Size group',
    icon: 'Picture',
    display_rank: 'Order in lists',
    purchase_price_cents: 'Purchase price',
    accounting_price_cents: 'Price',
    service_period_months: 'Service period',
    active: 'Active',
    lines: 'Items',
    record_number: 'Record number',
    total_cents: 'Total',
    status: 'Status',
    method: 'Confirmed',
    confirmed_name: 'Confirmed by',
    document_hash: 'Document hash',
    expires_at: 'Link valid until',
    link: 'Link',
    users: 'Users',
    active_users: 'Active users',
    administrators: 'Administrators',
    dormant: 'Unused for 90 days',
    no_sign_in: 'No sign-in recorded',
    format: 'Format',
    from: 'From',
    to: 'To',
    area: 'Area',
    event: 'Change',
    actor: 'Person',
    entity_type: 'Record type',
    entity_id: 'Record',
    rows: 'Changes',
    older_than: 'Older than',
  },
  sizeGroups: { CLOTHING: 'Clothing', SHOES: 'Shoes', NONE: 'No size' } as Record<string, string>,
  icons: {
    shoes: 'Shoes',
    jacket: 'Jacket',
    insulated_jacket: 'Insulated jacket',
    trousers: 'Trousers',
    vest: 'Vest',
    gloves: 'Gloves',
    helmet: 'Helmet',
    welding_helmet: 'Welding helmet',
    glasses: 'Glasses',
    ear: 'Ear protection',
    mask: 'Mask',
    other: 'Other',
  } as Record<string, string>,
  statuses: { ORDERED: 'Ordered', GIVEN: 'Given' } as Record<string, string>,
  methods: { ELECTRONIC: 'Electronically', PAPER: 'On paper', IN_PERSON: 'In person' } as Record<string, string>,
  yes: 'Yes',
  no: 'No',
  none: 'None',
  changed: 'Changed',
  months: (n: number) => plural(n, { one: '# month', other: '# months' }),
  items: (n: number) => plural(n, { one: '# item', other: '# items' }),
  roles: (n: number) => plural(n, { one: '# role', other: '# roles' }),
  permissionCount: (n: number) => plural(n, { one: '# permission', other: '# permissions' }),
  deviceOn: (browser: string, system: string) => `${browser} on ${system}`,
  unknownDevice: 'Unknown browser',
  // The detail of one change.
  field: 'Field',
  before: 'Before',
  after: 'After',
  when: 'When',
  who: 'Who',
  where: 'Made in',
  device: 'Device',
  reference: 'Reference',
  event: 'Event',
  record: 'Record',
  deleted: 'deleted',
  nobody: 'No one signed in',
  notRecorded: 'Not recorded',
  noDetails: 'No fields to show for this change.',
  changes: 'Changes',
  changesIntro: 'Who changed this record and when, newest first.',
  noChanges: 'No changes have been recorded yet.',
}

export type AuditText = typeof en

const lt: AuditText = {
  events: {
    'user.created': 'Naudotojas pridėtas',
    'user.updated': 'Naudotojo duomenys pakeisti',
    'user.roles_changed': 'Rolės pakeistos',
    'user.activated': 'Naudotojas aktyvuotas',
    'user.deactivated': 'Naudotojas deaktyvuotas',
    'user.password_changed': 'Slaptažodį pakeitė pats naudotojas',
    'user.password_reset': 'Slaptažodis nustatytas iš naujo',
    'user.deleted': 'Naudotojas ištrintas',
    'role.created': 'Rolė pridėta',
    'role.updated': 'Rolė pakeista',
    'role.deleted': 'Rolė ištrinta',
    'employee.created': 'Darbuotojas pridėtas',
    'employee.updated': 'Darbuotojo duomenys pakeisti',
    'employee.sizes_changed': 'Dydžiai pakeisti',
    'employee.deleted': 'Darbuotojas ištrintas',
    'catalogue.created': 'Prekė pridėta',
    'catalogue.updated': 'Prekės duomenys pakeisti',
    'catalogue.price_changed': 'Kaina pakeista',
    'catalogue.activated': 'Prekė aktyvuota',
    'catalogue.deactivated': 'Prekė deaktyvuota',
    'catalogue.deleted': 'Prekė ištrinta',
    'item_set.created': 'Prekių rinkinys pridėtas',
    'item_set.updated': 'Prekių rinkinys pakeistas',
    'item_set.deleted': 'Prekių rinkinys ištrintas',
    'order.ordered': 'Pažymėta kaip užsakyta',
    'order.confirmation_link_created': 'Sukurta patvirtinimo nuoroda',
    'order.given': 'Išduota',
    'order.deleted': 'Užsakymas ištrintas',
    'settings.supplier_chat_changed': 'Pakeista tiekėjo WhatsApp grupė',
    'access_review.completed': 'Prieiga peržiūrėta',
    'audit.exported': 'Audito žurnalas eksportuotas',
    'audit.purged': 'Ištrinti seni pakeitimai',
  },
  areas: {
    users: 'Naudotojai ir rolės',
    employees: 'Darbuotojai',
    catalogue: 'Prekių katalogas',
    item_sets: 'Prekių rinkiniai',
    orders: 'Užsakymai',
    settings: 'Nustatymai',
    security: 'Sauga',
    audit: 'Audito žurnalas',
  },
  sources: {
    workwear: 'Darbo drabužiai ir įranga',
    admin: 'Administravimas',
    api: 'API',
    public_link: 'Patvirtinimo nuoroda',
    system: 'Sistema',
  },
  fields: {
    first_name: 'Vardas',
    last_name: 'Pavardė',
    code: 'Kodas',
    preferred_language: 'Pageidaujama kalba',
    notes_changed: 'Pastabos',
    height_cm: 'Ūgis',
    clothing_size: 'Drabužių dydis',
    shoe_size: 'Avalynės dydis',
    name: 'Pavadinimas',
    email: 'El. paštas',
    language: 'Kalba',
    role_ids: 'Rolės',
    is_active: 'Aktyvus',
    description: 'Aprašymas',
    permissions: 'Teisės',
    details: 'Aprašas',
    size_group: 'Dydžių grupė',
    icon: 'Paveikslėlis',
    display_rank: 'Eilė sąrašuose',
    purchase_price_cents: 'Pirkimo kaina',
    accounting_price_cents: 'Kaina',
    service_period_months: 'Naudojimo laikotarpis',
    active: 'Aktyvus',
    lines: 'Prekės',
    record_number: 'Įrašo numeris',
    total_cents: 'Iš viso',
    status: 'Būsena',
    method: 'Patvirtinta',
    confirmed_name: 'Patvirtino',
    document_hash: 'Dokumento maiša',
    expires_at: 'Nuoroda galioja iki',
    link: 'Nuoroda',
    users: 'Naudotojai',
    active_users: 'Aktyvūs naudotojai',
    administrators: 'Administratoriai',
    dormant: 'Nesinaudota 90 dienų',
    no_sign_in: 'Prisijungimas neužfiksuotas',
    format: 'Formatas',
    from: 'Nuo',
    to: 'Iki',
    area: 'Sritis',
    event: 'Pakeitimas',
    actor: 'Asmuo',
    entity_type: 'Įrašo tipas',
    entity_id: 'Įrašas',
    rows: 'Pakeitimai',
    older_than: 'Senesni nei',
  },
  sizeGroups: { CLOTHING: 'Drabužiai', SHOES: 'Avalynė', NONE: 'Be dydžio' },
  icons: {
    shoes: 'Avalynė',
    jacket: 'Striukė',
    insulated_jacket: 'Šilta striukė',
    trousers: 'Kelnės',
    vest: 'Liemenė',
    gloves: 'Pirštinės',
    helmet: 'Šalmas',
    welding_helmet: 'Suvirintojo kaukė',
    glasses: 'Akiniai',
    ear: 'Klausos apsauga',
    mask: 'Kaukė',
    other: 'Kita',
  },
  statuses: { ORDERED: 'Užsakyta', GIVEN: 'Išduota' },
  methods: { ELECTRONIC: 'Elektroniniu būdu', PAPER: 'Popieriuje', IN_PERSON: 'Asmeniškai' },
  yes: 'Taip',
  no: 'Ne',
  none: 'Nėra',
  changed: 'Pakeista',
  months: (n: number) => plural(n, { one: '# mėnuo', few: '# mėnesiai', other: '# mėnesių' }),
  items: (n: number) => plural(n, { one: '# prekė', few: '# prekės', other: '# prekių' }),
  roles: (n: number) => plural(n, { one: '# rolė', few: '# rolės', other: '# rolių' }),
  permissionCount: (n: number) => plural(n, { one: '# teisė', few: '# teisės', other: '# teisių' }),
  deviceOn: (browser: string, system: string) => `${browser}, ${system}`,
  unknownDevice: 'Nežinoma naršyklė',
  field: 'Laukas',
  before: 'Buvo',
  after: 'Tapo',
  when: 'Kada',
  who: 'Kas',
  where: 'Kur atlikta',
  device: 'Įrenginys',
  reference: 'Nuoroda į užklausą',
  event: 'Įvykis',
  record: 'Įrašas',
  deleted: 'ištrintas',
  nobody: 'Niekas neprisijungęs',
  notRecorded: 'Neužfiksuota',
  noDetails: 'Šis pakeitimas neturi rodomų laukų.',
  changes: 'Pakeitimai',
  changesIntro: 'Kas ir kada keitė šį įrašą, naujausi pirmiau.',
  noChanges: 'Pakeitimų dar neužfiksuota.',
}

const ru: AuditText = {
  events: {
    'user.created': 'Пользователь добавлен',
    'user.updated': 'Данные пользователя изменены',
    'user.roles_changed': 'Роли изменены',
    'user.activated': 'Пользователь активирован',
    'user.deactivated': 'Пользователь деактивирован',
    'user.password_changed': 'Пароль изменён самим пользователем',
    'user.password_reset': 'Пароль сброшен',
    'user.deleted': 'Пользователь удалён',
    'role.created': 'Роль добавлена',
    'role.updated': 'Роль изменена',
    'role.deleted': 'Роль удалена',
    'employee.created': 'Сотрудник добавлен',
    'employee.updated': 'Данные сотрудника изменены',
    'employee.sizes_changed': 'Размеры изменены',
    'employee.deleted': 'Сотрудник удалён',
    'catalogue.created': 'Предмет добавлен',
    'catalogue.updated': 'Данные предмета изменены',
    'catalogue.price_changed': 'Цена изменена',
    'catalogue.activated': 'Предмет активирован',
    'catalogue.deactivated': 'Предмет деактивирован',
    'catalogue.deleted': 'Предмет удалён',
    'item_set.created': 'Набор предметов добавлен',
    'item_set.updated': 'Набор предметов изменён',
    'item_set.deleted': 'Набор предметов удалён',
    'order.ordered': 'Отмечено как заказанное',
    'order.confirmation_link_created': 'Создана ссылка для подтверждения',
    'order.given': 'Выдано',
    'order.deleted': 'Заказ удалён',
    'settings.supplier_chat_changed': 'Изменена группа поставщика в WhatsApp',
    'access_review.completed': 'Доступ проверен',
    'audit.exported': 'Журнал аудита выгружен',
    'audit.purged': 'Удалены старые изменения',
  },
  areas: {
    users: 'Пользователи и роли',
    employees: 'Сотрудники',
    catalogue: 'Каталог предметов',
    item_sets: 'Наборы предметов',
    orders: 'Заказы',
    settings: 'Настройки',
    security: 'Безопасность',
    audit: 'Журнал аудита',
  },
  sources: {
    workwear: 'Спецодежда и снаряжение',
    admin: 'Администрирование',
    api: 'API',
    public_link: 'Ссылка для подтверждения',
    system: 'Система',
  },
  fields: {
    first_name: 'Имя',
    last_name: 'Фамилия',
    code: 'Код',
    preferred_language: 'Предпочитаемый язык',
    notes_changed: 'Заметки',
    height_cm: 'Рост',
    clothing_size: 'Размер одежды',
    shoe_size: 'Размер обуви',
    name: 'Название',
    email: 'Эл. почта',
    language: 'Язык',
    role_ids: 'Роли',
    is_active: 'Активен',
    description: 'Описание',
    permissions: 'Права',
    details: 'Описание предмета',
    size_group: 'Группа размеров',
    icon: 'Картинка',
    display_rank: 'Порядок в списках',
    purchase_price_cents: 'Закупочная цена',
    accounting_price_cents: 'Цена',
    service_period_months: 'Срок службы',
    active: 'Активен',
    lines: 'Предметы',
    record_number: 'Номер записи',
    total_cents: 'Итого',
    status: 'Статус',
    method: 'Подтверждено',
    confirmed_name: 'Подтвердил',
    document_hash: 'Хеш документа',
    expires_at: 'Ссылка действует до',
    link: 'Ссылка',
    users: 'Пользователи',
    active_users: 'Активные пользователи',
    administrators: 'Администраторы',
    dormant: 'Не входили 90 дней',
    no_sign_in: 'Вход не зафиксирован',
    format: 'Формат',
    from: 'С',
    to: 'По',
    area: 'Раздел',
    event: 'Изменение',
    actor: 'Пользователь',
    entity_type: 'Тип записи',
    entity_id: 'Запись',
    rows: 'Изменения',
    older_than: 'Старше',
  },
  sizeGroups: { CLOTHING: 'Одежда', SHOES: 'Обувь', NONE: 'Без размера' },
  icons: {
    shoes: 'Обувь',
    jacket: 'Куртка',
    insulated_jacket: 'Утеплённая куртка',
    trousers: 'Брюки',
    vest: 'Жилет',
    gloves: 'Перчатки',
    helmet: 'Каска',
    welding_helmet: 'Маска сварщика',
    glasses: 'Очки',
    ear: 'Защита слуха',
    mask: 'Маска',
    other: 'Другое',
  },
  statuses: { ORDERED: 'Заказано', GIVEN: 'Выдано' },
  methods: { ELECTRONIC: 'Электронно', PAPER: 'На бумаге', IN_PERSON: 'Лично' },
  yes: 'Да',
  no: 'Нет',
  none: 'Нет',
  changed: 'Изменено',
  months: (n: number) => plural(n, { one: '# месяц', few: '# месяца', many: '# месяцев', other: '# месяца' }),
  items: (n: number) => plural(n, { one: '# предмет', few: '# предмета', many: '# предметов', other: '# предмета' }),
  roles: (n: number) => plural(n, { one: '# роль', few: '# роли', many: '# ролей', other: '# роли' }),
  permissionCount: (n: number) => plural(n, { one: '# право', few: '# права', many: '# прав', other: '# права' }),
  deviceOn: (browser: string, system: string) => `${browser}, ${system}`,
  unknownDevice: 'Неизвестный браузер',
  field: 'Поле',
  before: 'Было',
  after: 'Стало',
  when: 'Когда',
  who: 'Кто',
  where: 'Где сделано',
  device: 'Устройство',
  reference: 'Номер запроса',
  event: 'Событие',
  record: 'Запись',
  deleted: 'удалено',
  nobody: 'Без входа в систему',
  notRecorded: 'Не записано',
  noDetails: 'У этого изменения нет полей для показа.',
  changes: 'Изменения',
  changesIntro: 'Кто и когда менял эту запись, сначала новые.',
  noChanges: 'Изменений пока не записано.',
}

export const dictionaries = { en, lt, ru }

export const auditText = localized(dictionaries)
